(part "ATF13-2P-BM03"
    (packageRef "ATF132PBM03")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "654-ATF13-2P-BM03")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Amphenol-SINE-Systems/ATF13-2P-BM03?qs=%252B6g0mu59x7L1fHh%252BF9ugjw%3D%3D")
    (property "Manufacturer_Name" "Amphenol Sine Systems")
    (property "Manufacturer_Part_Number" "ATF13-2P-BM03")
    (property "Description" "Board Mount Header, Right Angle, AT, 2 Pin, Snap Fit, Tin plate")
    (property "Datasheet_Link" "https://www.amphenol-sine.com/pdf/datasheet/ATF13-2P-BM03.pdf")
    (property "symbolName1" "ATF13-2P-BM03")
)
